/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connectfour.frames;

/**
 *
 * @author SuperMommy
 */
public class QuoteMenuFrame extends javax.swing.JPanel {

    /**
     * Creates new form MainFrame
     */
    public QuoteMenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBody = new javax.swing.JPanel();
        jpTitle = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jpMenuItems = new javax.swing.JPanel();
        sundayButton = new javax.swing.JButton();
        mondayButton = new javax.swing.JButton();
        tuesdayButton = new javax.swing.JButton();
        wednesdayButton = new javax.swing.JButton();
        thursdayButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        fridayButton = new javax.swing.JButton();
        saturdayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtWelcome = new javax.swing.JTextArea();

        jpBody.setBackground(new java.awt.Color(13, 88, 117));
        jpBody.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jpTitle.setBorder(new javax.swing.border.MatteBorder(null));

        jlTitle.setBackground(new java.awt.Color(206, 221, 227));
        jlTitle.setFont(new java.awt.Font("Egyptian Slate Std Black", 0, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(13, 88, 117));
        jlTitle.setText("Quote Menu");
        jlTitle.setToolTipText("");

        javax.swing.GroupLayout jpTitleLayout = new javax.swing.GroupLayout(jpTitle);
        jpTitle.setLayout(jpTitleLayout);
        jpTitleLayout.setHorizontalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jpTitleLayout.setVerticalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpMenuItems.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sundayButton.setBackground(new java.awt.Color(13, 88, 117));
        sundayButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sundayButton.setForeground(new java.awt.Color(13, 88, 117));
        sundayButton.setText("Sunday");
        sundayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayButtonActionPerformed(evt);
            }
        });

        mondayButton.setBackground(new java.awt.Color(13, 88, 117));
        mondayButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mondayButton.setForeground(new java.awt.Color(13, 88, 117));
        mondayButton.setText("Monday");
        mondayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayButtonActionPerformed(evt);
            }
        });

        tuesdayButton.setBackground(new java.awt.Color(13, 88, 117));
        tuesdayButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tuesdayButton.setForeground(new java.awt.Color(13, 88, 117));
        tuesdayButton.setText("Tuesday");
        tuesdayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayButtonActionPerformed(evt);
            }
        });

        wednesdayButton.setBackground(new java.awt.Color(13, 88, 117));
        wednesdayButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wednesdayButton.setForeground(new java.awt.Color(13, 88, 117));
        wednesdayButton.setText("Wednesday");
        wednesdayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayButtonActionPerformed(evt);
            }
        });

        thursdayButton.setBackground(new java.awt.Color(13, 88, 117));
        thursdayButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        thursdayButton.setForeground(new java.awt.Color(13, 88, 117));
        thursdayButton.setText("Thursday");
        thursdayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(13, 88, 117));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitButton.setForeground(new java.awt.Color(13, 88, 117));
        exitButton.setLabel("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        fridayButton.setBackground(new java.awt.Color(13, 88, 117));
        fridayButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fridayButton.setForeground(new java.awt.Color(13, 88, 117));
        fridayButton.setText("Friday");
        fridayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayButtonActionPerformed(evt);
            }
        });

        saturdayButton.setBackground(new java.awt.Color(13, 88, 117));
        saturdayButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saturdayButton.setForeground(new java.awt.Color(13, 88, 117));
        saturdayButton.setText("Saturday");
        saturdayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemsLayout = new javax.swing.GroupLayout(jpMenuItems);
        jpMenuItems.setLayout(jpMenuItemsLayout);
        jpMenuItemsLayout.setHorizontalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addGroup(jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuItemsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wednesdayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sundayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mondayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tuesdayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thursdayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saturdayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fridayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpMenuItemsLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(exitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMenuItemsLayout.setVerticalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sundayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mondayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tuesdayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wednesdayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thursdayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fridayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saturdayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jtWelcome.setEditable(false);
        jtWelcome.setBackground(new java.awt.Color(13, 88, 117));
        jtWelcome.setColumns(20);
        jtWelcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jtWelcome.setLineWrap(true);
        jtWelcome.setRows(5);
        jtWelcome.setText("Welcome to the Quote Menu!  Choose a day of the week to see the quote of the day!");
        jtWelcome.setToolTipText("");
        jtWelcome.setWrapStyleWord(true);
        jtWelcome.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jtWelcome.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jtWelcome);

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addComponent(jpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sundayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayButtonActionPerformed
        // Go to Sunday Quote
    }//GEN-LAST:event_sundayButtonActionPerformed

    private void mondayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mondayButtonActionPerformed

    private void tuesdayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesdayButtonActionPerformed

    private void wednesdayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdayButtonActionPerformed

    private void thursdayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thursdayButtonActionPerformed

    private void fridayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fridayButtonActionPerformed

    private void saturdayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturdayButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton fridayButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpMenuItems;
    private javax.swing.JPanel jpTitle;
    private javax.swing.JTextArea jtWelcome;
    private javax.swing.JButton mondayButton;
    private javax.swing.JButton saturdayButton;
    private javax.swing.JButton sundayButton;
    private javax.swing.JButton thursdayButton;
    private javax.swing.JButton tuesdayButton;
    private javax.swing.JButton wednesdayButton;
    // End of variables declaration//GEN-END:variables
}
