/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package confour.frames;

import confour.ConnectFour;
import confour.enums.FrenchHelp;

/**
 *
 * @author Davy
 */
public class FrenchFrames extends javax.swing.JFrame {

    /**
     * Creates new form FrenchFrames
     */
    public FrenchFrames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpTitleBlue = new javax.swing.JPanel();
        jpTitleWhite = new javax.swing.JPanel();
        jlTitleTop = new javax.swing.JLabel();
        jlTitleBottom = new javax.swing.JLabel();
        jpTitleRed = new javax.swing.JPanel();
        jpMenuItems = new javax.swing.JPanel();
        jButtonGame = new javax.swing.JButton();
        jButtonPlayer = new javax.swing.JButton();
        jButtonBoard = new javax.swing.JButton();
        jButtonColumn = new javax.swing.JButton();
        jButtonMarker = new javax.swing.JButton();
        jButtonQuit = new javax.swing.JButton();
        jpTextArea = new javax.swing.JPanel();
        jTextArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpTitleBlue.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jpTitleBlueLayout = new javax.swing.GroupLayout(jpTitleBlue);
        jpTitleBlue.setLayout(jpTitleBlueLayout);
        jpTitleBlueLayout.setHorizontalGroup(
            jpTitleBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpTitleBlueLayout.setVerticalGroup(
            jpTitleBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpTitleWhite.setBackground(new java.awt.Color(255, 255, 255));

        jlTitleTop.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTitleTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitleTop.setText("Help Menu");

        jlTitleBottom.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jlTitleBottom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitleBottom.setText("In French!");

        javax.swing.GroupLayout jpTitleWhiteLayout = new javax.swing.GroupLayout(jpTitleWhite);
        jpTitleWhite.setLayout(jpTitleWhiteLayout);
        jpTitleWhiteLayout.setHorizontalGroup(
            jpTitleWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTitleWhiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTitleWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlTitleBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTitleTop, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpTitleWhiteLayout.setVerticalGroup(
            jpTitleWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleWhiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitleTop, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTitleBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpTitleRed.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jpTitleRedLayout = new javax.swing.GroupLayout(jpTitleRed);
        jpTitleRed.setLayout(jpTitleRedLayout);
        jpTitleRedLayout.setHorizontalGroup(
            jpTitleRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        jpTitleRedLayout.setVerticalGroup(
            jpTitleRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpMenuItems.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));

        jButtonGame.setText("Le Jeu");
        jButtonGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGameActionPerformed(evt);
            }
        });

        jButtonPlayer.setText("Joueur");
        jButtonPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayerActionPerformed(evt);
            }
        });

        jButtonBoard.setText("Plateau");
        jButtonBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBoardActionPerformed(evt);
            }
        });

        jButtonColumn.setText("Colonne");
        jButtonColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColumnActionPerformed(evt);
            }
        });

        jButtonMarker.setText("Jeton");
        jButtonMarker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarkerActionPerformed(evt);
            }
        });

        jButtonQuit.setText("Quitter");
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemsLayout = new javax.swing.GroupLayout(jpMenuItems);
        jpMenuItems.setLayout(jpMenuItemsLayout);
        jpMenuItemsLayout.setHorizontalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonColumn, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButtonMarker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpMenuItemsLayout.setVerticalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGame, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMarker, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButtonQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Consultez les choix d’aides disponibles.");
        jTextArea1.setToolTipText("");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea.setViewportView(jTextArea1);

        javax.swing.GroupLayout jpTextAreaLayout = new javax.swing.GroupLayout(jpTextArea);
        jpTextArea.setLayout(jpTextAreaLayout);
        jpTextAreaLayout.setHorizontalGroup(
            jpTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea)
                .addContainerGap())
        );
        jpTextAreaLayout.setVerticalGroup(
            jpTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpMenuItems, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTitleBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpTitleWhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpTitleRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpTitleWhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTitleBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTitleRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpMenuItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonQuitActionPerformed

    private void jButtonGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGameActionPerformed
        jTextArea1.setText(FrenchHelp.FRENCH_MENU_GAME.getMessage());
    }//GEN-LAST:event_jButtonGameActionPerformed

    private void jButtonPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayerActionPerformed
        jTextArea1.setText(FrenchHelp.FRENCH_MENU_PLAYER.getMessage());
    }//GEN-LAST:event_jButtonPlayerActionPerformed

    private void jButtonBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBoardActionPerformed
        jTextArea1.setText(FrenchHelp.FRENCH_MENU_BOARD.getMessage());
    }//GEN-LAST:event_jButtonBoardActionPerformed

    private void jButtonColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColumnActionPerformed
        jTextArea1.setText(FrenchHelp.FRENCH_MENU_COLUMN.getMessage());
    }//GEN-LAST:event_jButtonColumnActionPerformed

    private void jButtonMarkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarkerActionPerformed
        jTextArea1.setText(FrenchHelp.FRENCH_MENU_MARKER.getMessage());
    }//GEN-LAST:event_jButtonMarkerActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBoard;
    private javax.swing.JButton jButtonColumn;
    private javax.swing.JButton jButtonGame;
    private javax.swing.JButton jButtonMarker;
    private javax.swing.JButton jButtonPlayer;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jTextArea;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlTitleBottom;
    private javax.swing.JLabel jlTitleTop;
    private javax.swing.JPanel jpMenuItems;
    private javax.swing.JPanel jpTextArea;
    private javax.swing.JPanel jpTitleBlue;
    private javax.swing.JPanel jpTitleRed;
    private javax.swing.JPanel jpTitleWhite;
    // End of variables declaration//GEN-END:variables
}
